### ISSUE TITLE
would you please update code  to a newer version if tensorflow

### ISSUE THREAD

**Issue by SeekPoint** [shmsw25/qa-transfer#1]
since the the tf0.11 are not compatible with new CUDNN

**Comment by shmsw25** [comment]
Hi, 
Sorry I don't have codes with a newer version of tensorflow. However, the base code Bidaf has a newer version (v1.2) [here](https://github.com/allenai/bi-att-flow/tree/dev), so you can easily reimplement our model using this code.
Thanks.
